### ISSUE TITLE
Publish on SmartAPI

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/cloud-ws-metadata#1]
Let's get this service documented on SmartAPI

**Comment by mbdebian** [comment]
I think we should revisit this issue once we have more information on this.
What are your thoughts @sarala ?

**Comment by sarala** [comment]
Yeah, we will create a workflow for this at some point for DCPPC but we will promote our swagger version.

**Comment by mbdebian** [comment]
This issue is deprecated, as we currently have no strategy for managing OpenAPI specifications
