### ISSUE TITLE
Review infinite loop on some pages

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/cloud-ws-metadata#11]
I think I have detected that the metadata browser engine may get stuck in an infinite loop in some kind of pages I still need to identify.
We should try to add some kind of timeout for the Javascript engine, to prevent this from happening, otherwise it will never consider the page loaded, and the content analysis will never start.

**Comment by sarala** [comment]
Which link is it looping at? Is it this one - http://n2t.net/ark:/57799/b97957

**Comment by mbdebian** [comment]
I could not reproduce the error.

I've run the same dataset on a bigger machine, and the metadata service has been able to process all the request with no problem.

I think we'll keep this issue open for a while but, in case we can't reproduce the error, we'll just close it.

**Comment by mbdebian** [comment]
It was not possible to reproduce this error, so I'll close the issue.
